apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
    networking.gke.io/load-balancer-type: "Internal"
    #beta.cloud.google.com/backend-config: '{"default": "config-default"}'
  creationTimestamp: null
  labels:
    io.kompose.service: rair-front
  name: rair-front
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: rair-front
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: rair-front
  name: rair-front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rair-front
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/rair-local: "true"
        io.kompose.service: rair-front
        app: rair-front
    spec:
      containers:
        - image: rairprotocol/rair-front:cb1d2042ecd68d145e82147d71f03acb419b4a22
          name: rair-front
          imagePullPolicy: Always
          ports:
          - name: http-server 
            containerPort: 80
          envFrom:
          - configMapRef:
              name: rair-front-env
          resources: {}
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
status: {}
