apiVersion: v1
kind: ConfigMap
metadata:
  name: rair-node-env
data:
  PRODUCTION: "true"
  PINATA_KEY: ""
  ADMIN_NETWORK: matic
  ADMIN_CONTRACT: ""
  INFURA_PROJECT_ID: 92a88973a28d41318792f77451db4c5b
  SERVICE_HOST: api.rair.market
  DEFAULT_PRODUCT_COVER: https://rair.mypinata.cloud/ipfs/QmNtfjBAPYEFxXiHmY5kcPh9huzkwquHBcn9ZJHGe7hfaW
  GCP_PROJECT_ID: rair-market
  GCP_IMAGE_BUCKET_NAME: rair_images
  GCP_VIDEO_BUCKET_NAME: rair-videos
  GCP_GATEWAY: https://storage.googleapis.com
  IPFS_SERVICE: filebase
  IPFS_GATEWAY: http://rairipfs:8080/ipfs
  PINATA_GATEWAY: https://rair.mypinata.cloud/ipfs
  BINANCE_FACTORY_ADDRESS: "0xc76c3ebEA0aC6aC78d9c0b324f72CA59da36B9df"
  BINANCE_MINTER_ADDRESS: "0xC9eF9902fa24923A17326aDdb7da0E67fF46692a"
  GOERLI_FACTORY_ADDRESS: "0x12EF5310499318C90C55077241137Db52189b036"
  GOERLI_MINTER_ADDRESS: "0x14ef15A945b6Cae28f4FA3862E41d74E484Cd3B5"
  MATIC_MUMBAI_FACTORY_ADDRESS: "0x72639374fC9e4eec25839080763025A1d3E710EC"
  MATIC_MUMBAI_MINTER_ADDRESS: "0x4594D508cDa05D016571082d467889f4629e1f56"
  MATIC_MAINNET_FACTORY_ADDRESS: "0x74278C22BfB1DCcc3d42F8b71280C25691E8C157"
  MATIC_MAINNET_MINTER_ADDRESS: "0x781F15a23506CF28539EA057e3f33008E6339E49"
  ETHEREUM_MAINNET_FACTORY_ADDRESS: "0xA2A7e7636AB4374847074c147BE770624F43342E"
  ETHEREUM_MAINNET_MINTER_ADDRESS: "0x0Ce668D271b8016a785Bf146e58739F432300B12"
  ETHEREUM_DIAMOND_MARKETPLACE_ADDRESS: "0x5c31677c7E73F97020213690F736A8a2Ff922EBC"
  MATIC_TESTNET_RPC: https://polygon-mumbai.infura.io/v3/92a88973a28d41318792f77451db4c5b
  MATIC_MAINNET_RPC: https://polygon-mainnet.infura.io/v3/92a88973a28d41318792f77451db4c5b
  ETHEREUM_MAINNET_RPC: https://mainnet.infura.io/v3/92a88973a28d41318792f77451db4c5b
  ETHEREUM_TESTNET_GOERLI_RPC: https://goerli.infura.io/v3/92a88973a28d41318792f77451db4c5b
  BINANCE_TESTNET_RPC: https://data-seed-prebsc-1-s1.binance.org:8545/
  BINANCE_MAINNET_RPC: https://bsc-dataseed.binance.org/
  MONGO_LOG_COLLECTION: Log
  MORALIS_SERVER_TEST: https://ldz2lkdhowt1.usemoralis.com:2053/server
  MORALIS_SERVER_MAIN: https://y14jhwis7uao.moralishost.com:2053/server
  MORALIS_API_KEY_TEST: ""
  MORALIS_MASTER_KEY_TEST: ""
  REDIS_HOST: rair-redis
  REDIS_PORT: "6379"
  SESSION_SECRET: testsecret
  SESSION_TTL: "120"
  LOG_LEVEL: debug
  GENERATE_MONGO_URI_WITH_VAULT_CREDENTIAL_UTIL: "false"
  MONGO_DB_HOSTNAME: test
  MONGO_DB_NAME: test
  VAULT_URL: https://primary-dev.vault.9871e6c3-b0b9-479a-b392-eb69322d192a.aws.hashicorp.cloud:8200
  UPLOAD_PROGRESS_HOST: http://rair-node:5000
  BASE_BCN_URL: http://blockchain-event-listener:5001
  SUPER_ADMIN_VAULT_STORE: ""
  ZOOM_API_KEY: ""
  ZOOM_API_SECRET: ""
  ZOOM_MEETING_ID: ""
  ALCHEMY_API_KEY: ""
  AWS_ACCESS_KEY_ID: ""
  FILEBASE_BUCKET: juan
  AWS_SECRET_ACCESS_KEY: ""
